pipeline {
    agent any 
    stages {
        stage('Login to Docker Hub') {
            steps {
                sh '''
                cat ~/catkin_ws/.my_password.txt | 
                sudo docker login --username invokelee --password-stdin
                '''
            }
        }
        stage('Build Docker image') {
            steps {
                sh '''
                cd ~/catkin_ws/src/ros1_ci_docker
                sudo docker build -f Dockerfile -t invokelee/ros1-wp-test:1.0 /home/user
                '''
            }
        }
        stage('Docker compose up and Waypoint test') {
            steps {
                sh '''
                cd ~/catkin_ws/src/ros1_ci_docker
                sudo docker compose -f docker-compose-ros1_ci.yml up
                '''
            }
        }
        stage('Post task- Docker compose down') {
            steps {
                sh '''
                sleep 5
                cd ~/catkin_ws/src/ros1_ci_docker
                sudo docker compose -f docker-compose-ros1_ci.yml down
                '''
            }
        }
        stage('Done') {
            steps {
                sh '''
                echo "Docker build and run Pipeline job completed !"
                '''
            }
        }
    }
}